[2023-08-18T02:01:05.610+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T02:01:04.783907+00:00 [queued]>
[2023-08-18T02:01:05.618+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T02:01:04.783907+00:00 [queued]>
[2023-08-18T02:01:05.619+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-18T02:01:05.627+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2023-08-18 02:01:04.783907+00:00
[2023-08-18T02:01:05.631+0000] {standard_task_runner.py:57} INFO - Started process 2530 to run task
[2023-08-18T02:01:05.636+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_***_dag', 'spark_submit_task', 'manual__2023-08-18T02:01:04.783907+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/spark_jobs_dag.py', '--cfg-path', '/tmp/tmpt7pct5az']
[2023-08-18T02:01:05.637+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask spark_submit_task
[2023-08-18T02:01:05.690+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T02:01:04.783907+00:00 [running]> on host 15ea5e9ca941
[2023-08-18T02:01:05.761+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_***_dag' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-18T02:01:04.783907+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-18T02:01:04.783907+00:00'
[2023-08-18T02:01:05.772+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-08-18T02:01:05.773+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --name arrow-spark ./dags/utils/spark_processing.py
[2023-08-18T02:01:05.865+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-08-18T02:01:08.196+0000] {spark_submit.py:491} INFO - Traceback (most recent call last):
[2023-08-18T02:01:08.198+0000] {spark_submit.py:491} INFO - File "/opt/***/dags/utils/spark_processing.py", line 4, in <module>
[2023-08-18T02:01:08.198+0000] {spark_submit.py:491} INFO - from pandas import pd
[2023-08-18T02:01:08.199+0000] {spark_submit.py:491} INFO - ImportError: cannot import name 'pd' from 'pandas' (/home/***/.local/lib/python3.10/site-packages/pandas/__init__.py)
[2023-08-18T02:01:08.268+0000] {spark_submit.py:491} INFO - 23/08/18 02:01:08 INFO ShutdownHookManager: Shutdown hook called
[2023-08-18T02:01:08.270+0000] {spark_submit.py:491} INFO - 23/08/18 02:01:08 INFO ShutdownHookManager: Deleting directory /tmp/spark-57a7a917-7cf7-4315-b9dd-0e157322caad
[2023-08-18T02:01:08.326+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark ./dags/utils/spark_processing.py. Error code is: 1.
[2023-08-18T02:01:08.331+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=spark_***_dag, task_id=spark_submit_task, execution_date=20230818T020104, start_date=20230818T020105, end_date=20230818T020108
[2023-08-18T02:01:08.341+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task spark_submit_task (Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark ./dags/utils/spark_processing.py. Error code is: 1.; 2530)
[2023-08-18T02:01:08.386+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-18T02:01:08.407+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
