[2023-08-18T01:36:49.703+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T01:36:49.089069+00:00 [queued]>
[2023-08-18T01:36:49.714+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T01:36:49.089069+00:00 [queued]>
[2023-08-18T01:36:49.715+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-18T01:36:49.726+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2023-08-18 01:36:49.089069+00:00
[2023-08-18T01:36:49.730+0000] {standard_task_runner.py:57} INFO - Started process 374 to run task
[2023-08-18T01:36:49.735+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_***_dag', 'spark_submit_task', 'manual__2023-08-18T01:36:49.089069+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/spark_jobs_dag.py', '--cfg-path', '/tmp/tmpz9uii0st']
[2023-08-18T01:36:49.737+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask spark_submit_task
[2023-08-18T01:36:49.790+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T01:36:49.089069+00:00 [running]> on host 15ea5e9ca941
[2023-08-18T01:36:49.860+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_***_dag' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-18T01:36:49.089069+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-18T01:36:49.089069+00:00'
[2023-08-18T01:36:49.871+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-08-18T01:36:49.873+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --name arrow-spark utils/spark_processing.py
[2023-08-18T01:36:49.958+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-08-18T01:36:51.501+0000] {spark_submit.py:491} INFO - python3: can't open file '/opt/***/utils/spark_processing.py': [Errno 2] No such file or directory
[2023-08-18T01:36:51.512+0000] {spark_submit.py:491} INFO - 23/08/18 01:36:51 INFO ShutdownHookManager: Shutdown hook called
[2023-08-18T01:36:51.514+0000] {spark_submit.py:491} INFO - 23/08/18 01:36:51 INFO ShutdownHookManager: Deleting directory /tmp/spark-e368ed54-b586-4721-a118-74e113bf59c0
[2023-08-18T01:36:51.555+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark utils/spark_processing.py. Error code is: 2.
[2023-08-18T01:36:51.558+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=spark_***_dag, task_id=spark_submit_task, execution_date=20230818T013649, start_date=20230818T013649, end_date=20230818T013651
[2023-08-18T01:36:51.566+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task spark_submit_task (Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark utils/spark_processing.py. Error code is: 2.; 374)
[2023-08-18T01:36:51.583+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-18T01:36:51.599+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
