[2023-08-09T06:48:56.510+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-09T06:48:55.481081+00:00 [queued]>
[2023-08-09T06:48:56.518+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-09T06:48:55.481081+00:00 [queued]>
[2023-08-09T06:48:56.519+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-09T06:48:56.528+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2023-08-09 06:48:55.481081+00:00
[2023-08-09T06:48:56.532+0000] {standard_task_runner.py:57} INFO - Started process 56 to run task
[2023-08-09T06:48:56.537+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_***_dag', 'spark_submit_task', 'manual__2023-08-09T06:48:55.481081+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/spark_jobs_dag.py', '--cfg-path', '/tmp/tmpd0ftac6u']
[2023-08-09T06:48:56.538+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask spark_submit_task
[2023-08-09T06:48:56.597+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-09T06:48:55.481081+00:00 [running]> on host efce79e2ed4f
[2023-08-09T06:48:56.670+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_***_dag' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-09T06:48:55.481081+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-09T06:48:55.481081+00:00'
[2023-08-09T06:48:56.682+0000] {spark_submit.py:218} INFO - Could not load connection string spark_local, defaulting to yarn
[2023-08-09T06:48:56.683+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark /opt/***/dags/spark_processing.py
[2023-08-09T06:48:56.778+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-08-09T06:48:56.781+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64//bin/java: No such file or directory
[2023-08-09T06:48:56.782+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2023-08-09T06:48:56.798+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark /opt/***/dags/spark_processing.py. Error code is: 1.
[2023-08-09T06:48:56.801+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=spark_***_dag, task_id=spark_submit_task, execution_date=20230809T064855, start_date=20230809T064856, end_date=20230809T064856
[2023-08-09T06:48:56.810+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task spark_submit_task (Cannot execute: spark-submit --master yarn --name arrow-spark /opt/***/dags/spark_processing.py. Error code is: 1.; 56)
[2023-08-09T06:48:56.835+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-09T06:48:56.852+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
