[2023-08-18T01:34:22.316+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T01:34:21.698579+00:00 [queued]>
[2023-08-18T01:34:22.324+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T01:34:21.698579+00:00 [queued]>
[2023-08-18T01:34:22.325+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-18T01:34:22.334+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2023-08-18 01:34:21.698579+00:00
[2023-08-18T01:34:22.337+0000] {standard_task_runner.py:57} INFO - Started process 202 to run task
[2023-08-18T01:34:22.342+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_***_dag', 'spark_submit_task', 'manual__2023-08-18T01:34:21.698579+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/spark_jobs_dag.py', '--cfg-path', '/tmp/tmpu8l8af99']
[2023-08-18T01:34:22.343+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask spark_submit_task
[2023-08-18T01:34:22.390+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T01:34:21.698579+00:00 [running]> on host 15ea5e9ca941
[2023-08-18T01:34:22.456+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_***_dag' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-18T01:34:21.698579+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-18T01:34:21.698579+00:00'
[2023-08-18T01:34:22.466+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-08-18T01:34:22.468+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master localhost:8090 --name arrow-spark utils/spark_processing.py
[2023-08-18T01:34:22.552+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-08-18T01:34:23.773+0000] {spark_submit.py:491} INFO - python3: can't open file '/opt/***/utils/spark_processing.py': [Errno 2] No such file or directory
[2023-08-18T01:34:23.782+0000] {spark_submit.py:491} INFO - 23/08/18 01:34:23 INFO ShutdownHookManager: Shutdown hook called
[2023-08-18T01:34:23.784+0000] {spark_submit.py:491} INFO - 23/08/18 01:34:23 INFO ShutdownHookManager: Deleting directory /tmp/spark-376064a6-46b2-455d-a886-b39202e9c3e8
[2023-08-18T01:34:23.838+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master localhost:8090 --name arrow-spark utils/spark_processing.py. Error code is: 2.
[2023-08-18T01:34:23.842+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=spark_***_dag, task_id=spark_submit_task, execution_date=20230818T013421, start_date=20230818T013422, end_date=20230818T013423
[2023-08-18T01:34:23.851+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task spark_submit_task (Cannot execute: spark-submit --master localhost:8090 --name arrow-spark utils/spark_processing.py. Error code is: 2.; 202)
[2023-08-18T01:34:23.863+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-18T01:34:23.880+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
