[2023-08-15T03:00:48.173+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-15T03:00:47.313800+00:00 [queued]>
[2023-08-15T03:00:48.178+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-15T03:00:47.313800+00:00 [queued]>
[2023-08-15T03:00:48.179+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-15T03:00:48.184+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2023-08-15 03:00:47.313800+00:00
[2023-08-15T03:00:48.187+0000] {standard_task_runner.py:57} INFO - Started process 326 to run task
[2023-08-15T03:00:48.190+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_***_dag', 'spark_submit_task', 'manual__2023-08-15T03:00:47.313800+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/spark_jobs_dag.py', '--cfg-path', '/tmp/tmpzae97rdp']
[2023-08-15T03:00:48.191+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask spark_submit_task
[2023-08-15T03:00:48.227+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-15T03:00:47.313800+00:00 [running]> on host 4df606623084
[2023-08-15T03:00:48.272+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_***_dag' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-15T03:00:47.313800+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-15T03:00:47.313800+00:00'
[2023-08-15T03:00:48.280+0000] {spark_submit.py:218} INFO - Could not load connection string spark_local, defaulting to yarn
[2023-08-15T03:00:48.281+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark spark_processing.py
[2023-08-15T03:00:48.336+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-08-15T03:00:48.338+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-class: line 71: /Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home/bin/java: No such file or directory
[2023-08-15T03:00:48.339+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2023-08-15T03:00:48.348+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark spark_processing.py. Error code is: 1.
[2023-08-15T03:00:48.351+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=spark_***_dag, task_id=spark_submit_task, execution_date=20230815T030047, start_date=20230815T030048, end_date=20230815T030048
[2023-08-15T03:00:48.357+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task spark_submit_task (Cannot execute: spark-submit --master yarn --name arrow-spark spark_processing.py. Error code is: 1.; 326)
[2023-08-15T03:00:48.366+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-15T03:00:48.377+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
